# Generated by Django 5.2.3 on 2025-07-28 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(choices=[('8-9', '8:00 AM to 9:00 AM'), ('9-10', '9:00 AM to 10:00 AM'), ('10-11', '10:00 AM to 11:00 AM'), ('11-12', '11:00 AM to 12:00 PM'), ('1-2', '1:00 PM to 2:00 PM'), ('2-3', '2:00 PM to 3:00 PM'), ('3-4', '3:00 PM to 4:00 PM'), ('4-5', '4:00 PM to 5:00 PM'), ('5-6', '5:00 PM to 6:00 PM'), ('6-7', '6:00 PM to 7:00 PM'), ('7-8', '7:00 PM to 8:00 PM'), ('8-9', '8:00 PM to 9:00 PM')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.course')),
                ('staff', models.ForeignKey(blank=True, limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_courses_as_staff', to=settings.AUTH_USER_MODEL)),
                ('students', models.ForeignKey(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_courses_as_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
