# Generated by Django 5.2.3 on 2025-07-29 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_user_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='course',
        ),
    ]
