# Generated by Django 5.2.4 on 2025-08-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_user_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='batch',
            field=models.CharField(blank=True, choices=[('8-9', '8:00 AM to 9:00 AM'), ('9-10', '9:00 AM to 10:00 AM'), ('10-11', '10:00 AM to 11:00 AM'), ('11-12', '11:00 AM to 12:00 PM'), ('1-2', '1:00 PM to 2:00 PM'), ('2-3', '2:00 PM to 3:00 PM'), ('3-4', '3:00 PM to 4:00 PM'), ('4-5', '4:00 PM to 5:00 PM'), ('5-6', '5:00 PM to 6:00 PM'), ('6-7', '6:00 PM to 7:00 PM'), ('7-8', '7:00 PM to 8:00 PM'), ('8-9', '8:00 PM to 9:00 PM')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
