# Generated by Django 5.2.4 on 2025-08-05 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_user_course_alter_user_batch_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='course',
        ),
    ]
