# Generated by Django 5.2.4 on 2025-08-05 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_user_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='batch',
        ),
    ]
