# Generated by Django 5.2.4 on 2025-08-11 14:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_user_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='trainer',
        ),
        migrations.AddField(
            model_name='course',
            name='trainer',
            field=models.ManyToManyField(limit_choices_to={'role': 'staff'}, related_name='trainer_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
