# Generated by Django 5.2.4 on 2025-08-11 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_course_trainer_course_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='trainer',
        ),
        migrations.AddField(
            model_name='course',
            name='trainers',
            field=models.ManyToManyField(limit_choices_to={'role': 'staff'}, related_name='courses_as_trainer', to=settings.AUTH_USER_MODEL),
        ),
    ]
