# Generated by Django 5.2.4 on 2025-08-13 13:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_course_trainer_course_trainers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedcourse',
            name='staff',
        ),
        migrations.AddField(
            model_name='bookedcourse',
            name='staff',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'staff'}, null=True, related_name='booked_courses_as_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
