# Generated by Django 5.2.4 on 2025-08-13 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_bookedcourse_staff_bookedcourse_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedcourse',
            name='staff',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'staff'}, related_name='booked_courses_as_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
